version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Management Plugin
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persist RabbitMQ data
      - ./definitions.json:/etc/rabbitmq/definitions.json  # Mount custom RabbitMQ definitions

  be:
    build:
      context: .
      dockerfile: deploy/Dockerfile.be
    ports:
      - "8765:8765"  # WebSocket server port
    depends_on:
      - rabbitmq

  solver:
    build:
      context: .
      dockerfile: deploy/Dockerfile.solver
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
